# Generated by Django 5.2.1 on 2025-05-12 09:19

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('image_front', models.ImageField(upload_to='img_post')),
                ('image_back', models.ImageField(upload_to='img_post')),
                ('description', models.TextField(max_length=300)),
                ('conditions', models.CharField(choices=[('Mint', 'Mint'), ('Near mint', 'Near mint'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Light played', 'Light played'), ('Played', 'Played'), ('Poor', 'Poor')], max_length=20)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('n_of_like', models.IntegerField(default=0)),
                ('n_of_wishlist', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=30)),
                ('surname', models.CharField(blank=True, max_length=30)),
                ('img_profilo', models.ImageField(default='img_profilo_default.jpg', upload_to='img_profilo')),
                ('nationality', models.CharField(blank=True, help_text='Codice ISO della nazione (es. IT, US, FR)', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
