# Generated by Django 5.1.7 on 2025-03-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_profilo_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='descrizione',
        ),
    ]
