# Generated by Django 5.1.7 on 2025-04-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_descrizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, help_text='Codice ISO della nazione (es. IT, US, FR)', max_length=2),
        ),
    ]
