# Generated by Django 5.2 on 2025-04-28 19:43

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_name_profile_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=80)),
                ('image_front', models.ImageField(upload_to='img_post')),
                ('image_back', models.ImageField(upload_to='img_post')),
                ('description', models.TextField(max_length=300)),
                ('conditions', models.CharField(choices=[('Mint', 'Mint'), ('Near mint', 'Near mint'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Light played', 'Light played'), ('Played', 'Played'), ('Poor', 'Poor')], max_length=20)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('n_of_like', models.IntegerField(default=0)),
                ('n_of_wishlist', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
